# Generated by Django 5.0.13 on 2025-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
