# Generated by Django 5.0.14 on 2025-04-28 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0003_alter_deck_active_alter_deck_commander_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
        migrations.AlterField(
            model_name="deck",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
