# Generated by Django 5.0.14 on 2025-04-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("decks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("win_condition", models.CharField(max_length=70)),
                ("notes", models.TextField(max_length=280)),
                ("draw", models.BooleanField(default=False)),
                (
                    "first_elim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_first_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turn_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mulligan",
                    models.IntegerField(
                        choices=[
                            (7, "None"),
                            (6, "Mull to 6"),
                            (5, "Mull to 5"),
                            (4, "Mull to 4"),
                            (3, "Mull to 3"),
                            (2, "Mull to 2"),
                        ],
                        default=7,
                    ),
                ),
                ("concede", models.BooleanField(default=False)),
                (
                    "deck",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decks_in_this_game",
                        to="decks.deck",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_played_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
