# Generated by Django 5.0.13 on 2025-04-22 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_playergame_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="draw",
            field=models.BooleanField(default=False, verbose_name="Draw"),
        ),
        migrations.AlterField(
            model_name="game",
            name="first_elim",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_first_out",
                to=settings.AUTH_USER_MODEL,
                verbose_name="First Out",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="turn_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_started",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Went First",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="win_condition",
            field=models.CharField(max_length=70, verbose_name="Win Condition"),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_won",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Winner",
            ),
        ),
    ]
