# Generated by Django 5.0.13 on 2025-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_draw_alter_game_first_elim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergame",
            name="concede",
            field=models.BooleanField(default=False, verbose_name="Concession"),
        ),
    ]
