# Generated by Django 5.0.14 on 2025-04-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_winner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="draw",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Draw"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="first_elim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_first_out",
                to=settings.AUTH_USER_MODEL,
                verbose_name="First Out",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="turn_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_started",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Went First",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="win_condition",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Win Condition"
            ),
        ),
    ]
