# Generated by Django 5.0.14 on 2025-04-29 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0004_alter_deck_active_alter_deck_created_by"),
        ("games", "0007_alter_playergame_deck_alter_playergame_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergame",
            name="deck",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_games",
                to="decks.deck",
            ),
        ),
        migrations.AlterField(
            model_name="playergame",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
